### ISSUE TITLE
icon: dark grey on black

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#12]
The app icon shows as dark grey on black on my home screen. Can we change the icon's background to white? If not, I can create an alternate graphic with white in place of the dark grey squares and text. Let me know.

**Comment by nadia-dev** [comment]
@yochannah, if you can send me the icon you would like to see, that would be great. I just used something I found on the Internet...

**Comment by yochannah** [comment]
are there any size requirements? I've added a few logos here: https://github.com/intermine/design-materials/tree/master/logos/intermine/squareish and I think generally prefer the white background ones...

**Comment by nadia-dev** [comment]
These look fine, I’ll try them and see if something needs to be changed.
