### ISSUE TITLE
Bug when switching mines then returning to a mine-specific screen

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#22]
1. Run a template for a given mine (let's say hymenopteramine) and view results.
2. Click on lists, favourites, or logon - any screen that has the mine selector available.
3. Select a different mine - let's say phytomine.
4. Return to templates - you'll see the old hymenopteramine results with the title and branding for phytomine. 

See screenshots attached - same results, two different mine headers. Sometimes I've ended up with *both* mine titles in the header (Phytomine hymenopteramine) but I'm not sure how to consistently reproduce that. 

![image](https://user-images.githubusercontent.com/9271438/27285989-7fe50ed0-54f6-11e7-8c46-aac1facc974a.png)
![image](https://user-images.githubusercontent.com/9271438/27285997-88cc7614-54f6-11e7-81e1-42d70cd0a528.png)

**Comment by nadia-dev** [comment]
Fix in relation with another bug
