### ISSUE TITLE
Phytomine lists return no results found

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#23]
the lists show counts on the lists of lists page, but when I try to view the contents it says no results found.The lists do have contents.

Example list A. thaliana pollen hs no results in the app: 
https://phytozome.jgi.doe.gov/phytomine/bagDetails.do?scope=all&bagName=A.thaliana+Pollen

**Comment by nadia-dev** [comment]
Other mines are using http, but phytomine requires https
