### ISSUE TITLE
Lists page

### ISSUE THREAD

**Issue by nadia-dev** [intermine/intermine-ios#30]
@yochannah, Should click on list lead to Mine’s list analysis page?

**Comment by nadia-dev** [comment]
@yochannah, also - how can we access list detail page if one exists. The result one gets from /lists call contains lists like this: lists": [{
		"dateCreated": "2013-03-14T07:17:35-0400",
		"size": 6,
		"authorized": false,
		"name": "Bmp disease lists - Thu Mar 14 2013",
		"description": "",
		"type": "DiseaseTerm",
		"title": "Bmp disease lists - Thu Mar 14 2013",
		"status": "CURRENT",
		"timestamp": 1363259855907,
		"tags": []
	}]
There is no id one can use to fetch details for the list...

**Comment by yochannah** [comment]
Ok, the list analysis page makes the most sense probably. To link in to a mine's list analysis page, use this link format: `http://www.flymine.org/flymine/bagDetails.do?scope=all&bagName=H.+sapiens+orthologues+of+FlyTF_site_specific_1` 

where `bagName` is the name of the list. More docs about linking into intermines here, although they don't apply to this specific scenario: http://intermine.readthedocs.io/en/latest/webapp/linking-in/

**Comment by nadia-dev** [comment]
@yochannah, do i understand it correctly that from list which comes from API like this:
{
            "dateCreated": "2017-06-13T06:37:39-0700",
            "size": 6604,
            "authorized": false,
            "name": "ALL_Verified_Uncharacterized_Dubious_ORFs",
            "description": "This List includes ALL ORFs",
            "type": "Gene",
            "title": "ALL_Verified_Uncharacterized_Dubious_ORFs",
            "status": "CURRENT",
            "timestamp": 1497361059587,
            "tags": []
        }
if will have to make a query:
bagName=ALL_Verified_Uncharacterized_Dubious_ORFs
?
