### ISSUE TITLE
Feature request - Google sign in

### ISSUE THREAD

**Issue by nadia-dev** [intermine/intermine-ios#31]
@yochannah, there is a request to login w/google account. Is it possible? For now the users log in w/Intermine accounts for specific mines. Is google sign in integrated w/Intermine at all?

**Comment by julie-sullivan** [comment]
We do have it set up so you can use your google log in as your mine account, see the "sign in with google" link:

http://www.flymine.org/flymine/login.do

But I am not sure how that would work with the app. 

To get that link to work in FlyMine, I had to tell google my URL and provide a secret key by request from that same URL. Is there a way we can tell google this is the "same" application?

Also, each mine has to set up the google sign in themselves, and I am sure not everyone has done so. So it won't be available for all mines.

**Comment by yochannah** [comment]
I'd suggest we leave this ticket for now. The eventual move to BlueGenes http://bluegenes.apps.intermine.org/ will probably involve a change to the way we authenticate but we don't really know what it is yet.
