### ISSUE TITLE
Use DisplayNames where possible

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#4]
You can find display names in the model for each mine to make field names more human friendly - i.e. `secondaryIdentifier` becomes "Secondary Identifier" 

![image](https://user-images.githubusercontent.com/9271438/27035841-b0314224-4f7a-11e7-9448-a4818e5df0d1.png)

**Comment by nadia-dev** [comment]
@yochannah, where can i find an instance of it in the app? is it for search results or templates/lists?

**Comment by yochannah** [comment]
Sorry, I should have been clearer! Places that are affected:

- [ ] Search results (list)
- [ ] Search results (individual result page)
- [ ] Favourites

Lists seems ok and I can't check templates right now - I think I'm seeing a template result and I can't figure out how to get out of it (that'll be a separate bug lol)

**Comment by nadia-dev** [comment]
Ok. I added the issue for template result page

**Comment by nadia-dev** [comment]
@yochannah, i am not sure how we can fix it. I am using the result of the http request (for example, `http://www.mousemine.org/mousemine/service/search?q=c2c&start=0&size=10&format=json&facet_Category=Gene`), and it only contains primary identifier. For example, the response for the previous request is:
"facets": {
		"Category": {
			"Gene": 1
		},
		"organism.shortName": {
			"M. musculus": 1
		},
		"pathways.name": {}
	},
	"results": [{
		"id": 12875412,
		"type": "Gene",
		"fields": {
			"symbol": "Scgb2b20",
			"sequenceOntologyTerm.name": "protein_coding_gene",
			"name": "secretoglobin, family 2B, member 20",
			"organism.name": "Mus musculus",
			"primaryIdentifier": "MGI:3514009"
		},
		"relevance": 0.24681501
	}],
	"executionTime": "2017.04.25 18:01::31",
	"wasSuccessful": true,
	"error": null,
	"statusCode": 200
}

**Comment by yochannah** [comment]
Whoops, I didn't mean specifically secondary identifier. I mean that in screens like this one, use display names rather than computer names in general - so for this screenshot:

"Molecular Weight" rather than "molecularWeight"
"Type" rather than "type"
"Primary Identifier" rather than "primaryIdentifier"

This info (converting from the computer names to the display names) can be gleaned from the model.

![image](https://user-images.githubusercontent.com/9271438/27283794-e7b0a280-54ed-11e7-9537-ee40e9f309b8.png)

Does that make more sense?
