### ISSUE TITLE
Templates - Obsolete constrains

### ISSUE THREAD

**Issue by nadia-dev** [intermine/intermine-ios#69]
To filter out obsolete constraints, we may have to hard-code them. @yochannah, maybe some more comments, as i don't fully understand this...

**Comment by yochannah** [comment]
Specifically this was regarding the following suggestions from Gos regarding a template:

> - in YeastMine only certain constraints are visible to the end-user unless they click
   "Edit Query" and so this hides the Obsolete constraints - would it be possible to do
   likewise? i.e. in this case only have an input field for "GO Term Identifier"?
   I expect that the template ought to self-describe which fields/ constraints are visible
   and which are invisible.
> - If you were optionally to show all the constraints it would be nice to pick up the
   "Obsolete" as well as the "IS NULL" and "false".

I'm guessing the hidden obsolete constraint is specified via a config file somewhere, or possibly hard coded into the codebase, and probably not available via the web services. @julie-sullivan @kkarra is this correct?

**Comment by nadia-dev** [comment]
I used "editable" field of the constraint object to decide whether a constraint should be shown to the user of not. @yochannah, is this correct? If yes, we can do this feature in this iteration of the app - it is easy :)

**Comment by yochannah** [comment]
Hmm, I'm not sure but I will try to find out today!

**Comment by rachellyne** [comment]
Yes, i think that's correct - anything editable should be shown. Some constraints are fixed and therefore do not need to be shown.

**Comment by yochannah** [comment]
thanks @rachellyne !
