### ISSUE TITLE
Refine search screen: re-run search button?

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#7]
This might need to be discounted as I don't use iOS as much as I use Android so I could be used to different patterns, but I feel like there needs to be some sort of call-to-action button in the refine search screen. going back does seem to apply the filters in the top left, but an "apply filters" button (or similar) might be more logical?

**Comment by nadia-dev** [comment]
@yochannah, do you want to rename the "back button" or you would like to see a separate CTA on refine search screen?

**Comment by yochannah** [comment]
separate cta I think?
