### ISSUE TITLE
loading screen still hangs

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#70]
the updates to the app are looking really nice! Unfortunately both Gos and I have found that while the app launches ok now, if you let the screen sleep or go to a different app and come back to intermine, the green loader spins endlessly. Fix right now: I have to double tap home and kill the intermine ios, then when I re-load intermine it'll work again.

**Comment by nadia-dev** [comment]
didFinishLaunchingWithOptions method where we have the logic to hide the loading screen is only executed with a new launch. Coming back from background doesn't call this method. Use applicationWillEnterForeground method.
