### ISSUE TITLE
Templates - stop repeated API calls

### ISSUE THREAD

**Issue by nadia-dev** [intermine/intermine-ios#84]

**Comment by nadia-dev** [comment]
Example: tabbing between templates and lists
The app should not call templates more than once within a 2 or 3 second period

**Comment by yochannah** [comment]
This fix is a work around to avoid crashing intermines that don't have the fix explored here: https://github.com/intermine/intermine/issues/1648

**Comment by joystate** [comment]
I am not sure how to test it other than run it against FlyMine and see...

**Comment by nadia-dev** [comment]
Currently the application is making too many requests, because of the notification system. This needs to be changed.
