### ISSUE TITLE
add ipad icons

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ios#97]
I was in the process of setting up the app store listing for this app. I have most things done, I think, but when I try to validate the app archive, it tells me we're missing ipad icons. Screenshot attached.

@joystate  I wasn't sure where to put the files - can you help? I can provide icons at those exact sizes if needed.

**Comment by yochannah** [comment]
![image](https://user-images.githubusercontent.com/9271438/29318895-cf94e158-81c9-11e7-812c-f9b33a859cc3.png)

**Comment by nadia-dev** [comment]
Right, because we made it universal. I'll put something in asap. I think at the end we need a vector images for icons and for the logo used in the app, as they will look better on devices with higher resolution.

**Comment by yochannah** [comment]
What format - SVG? other?

**Comment by nadia-dev** [comment]
Yes, I think svg should look better.

**Comment by yochannah** [comment]
here's the square svg logo: https://github.com/intermine/design-materials/blob/master/logos/intermine/squareish/square.svg

**Comment by yochannah** [comment]
there's also a white backgrounded square svg now: https://github.com/intermine/design-materials/blob/master/logos/intermine/squareish/square-white.svg and a full logo: https://github.com/intermine/design-materials/blob/master/logos/intermine/InterMine-logo.svg

**Comment by nadia-dev** [comment]
These are great. Do we also have this one?

**Comment by nadia-dev** [comment]
The last one we need is the white text logo

**Comment by yochannah** [comment]
Here you go!

https://github.com/intermine/design-materials/blob/master/logos/intermine/InterMine-logo-monochrome.svg
